### PR TITLE
Fix missing line comment

### PR DESCRIPTION
**Pull request by GalDude33**
There was a missing '#' sign in front of comment, this is causing errors when trying to import the repo.

### CODE REVIEW

**Comment by GalDude33** [comment]
@googlebot I signed it!

**Comment by GalDude33** [comment]
@googlebot I signed it!

**Comment by chr-wei** [comment]
@michellelivne Could you please merge this pull request? Wanted to propose the same change. Your package is broken and cannot be imported.

**Comment by chr-wei** [comment]
Thank you very much!

**Pull request merged**
